package idlcmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"go-solana-anchor/idl"
)

// GenOpts configures code generation.
type GenOpts struct {
	Package string // Go package name for generated code
	Output  string // Output directory
}

// Generate reads the IDL from inputPath and writes generated Go files to opts.Output.
func Generate(inputPath string, opts GenOpts) error {
	data, err := os.ReadFile(inputPath)
	if err != nil {
		return fmt.Errorf("read IDL: %w", err)
	}
	parsed, err := idl.Parse(data)
	if err != nil {
		return fmt.Errorf("parse IDL: %w", err)
	}

	if opts.Package == "" {
		opts.Package = toSnake(parsed.Metadata.Name)
	}
	if opts.Output == "" {
		opts.Output = "."
	}
	if err := os.MkdirAll(opts.Output, 0755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	// Generate types.go
	typesContent, err := generateTypes(parsed, opts.Package)
	if err != nil {
		return fmt.Errorf("generate types: %w", err)
	}
	if err := os.WriteFile(filepath.Join(opts.Output, "types.go"), []byte(typesContent), 0644); err != nil {
		return err
	}

	// Generate client.go
	clientContent, err := generateClient(parsed, opts.Package)
	if err != nil {
		return fmt.Errorf("generate client: %w", err)
	}
	if err := os.WriteFile(filepath.Join(opts.Output, "client.go"), []byte(clientContent), 0644); err != nil {
		return err
	}

	// Generate errors.go if IDL has errors
	if len(parsed.Errors) > 0 {
		errorsContent, err := generateErrors(parsed, opts.Package)
		if err != nil {
			return fmt.Errorf("generate errors: %w", err)
		}
		if err := os.WriteFile(filepath.Join(opts.Output, "errors.go"), []byte(errorsContent), 0644); err != nil {
			return err
		}
	}

	return nil
}

func toPascal(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func toCamel(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func toSnake(s string) string {
	var buf strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			buf.WriteByte('_')
		}
		buf.WriteRune(r)
	}
	return strings.ToLower(buf.String())
}

func idlTypeToGo(ty interface{}) string {
	switch v := ty.(type) {
	case string:
		return mapIDLTypeToGo(v)
	case map[string]interface{}:
		if vec, ok := v["vec"].(string); ok {
			return "[]" + idlTypeToGo(vec)
		}
		if opt, ok := v["option"]; ok {
			return "*" + idlTypeToGo(opt)
		}
		if def, ok := v["defined"].(string); ok {
			return toPascal(def)
		}
		if arr, ok := v["array"].([]interface{}); ok && len(arr) == 2 {
			if n, ok := arr[1].(json.Number); ok {
				sz, _ := n.Int64()
				return fmt.Sprintf("[%d]", sz) + idlTypeToGo(arr[0])
			}
		}
		return "interface{}"
	default:
		return "interface{}"
	}
}

func mapIDLTypeToGo(s string) string {
	switch s {
	case "u8":
		return "uint8"
	case "u16":
		return "uint16"
	case "u32":
		return "uint32"
	case "u64":
		return "uint64"
	case "i8":
		return "int8"
	case "i16":
		return "int16"
	case "i32":
		return "int32"
	case "i64":
		return "int64"
	case "bool":
		return "bool"
	case "string":
		return "string"
	case "pubkey":
		return "solana.PublicKey"
	default:
		return toPascal(s)
	}
}

func generateTypes(parsed *idl.IDL, pkg string) (string, error) {
	var buf strings.Builder
	buf.WriteString(fmt.Sprintf("// Code generated by go-anchor. DO NOT EDIT.\n\npackage %s\n\n", pkg))
	buf.WriteString("import \"github.com/gagliardetto/solana-go\"\n\n")

	// Generate structs from types
	for _, t := range parsed.Types {
		if t.Type.Kind != "struct" {
			continue
		}
		buf.WriteString(fmt.Sprintf("// %s account/type from IDL\n", t.Name))
		buf.WriteString(fmt.Sprintf("type %s struct {\n", t.Name))
		for _, f := range t.Type.Fields {
			goTy := idlTypeToGo(f.Type)
			buf.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", toPascal(f.Name), goTy, f.Name))
		}
		buf.WriteString("}\n\n")
	}

	// Generate event structs
	for _, e := range parsed.Events {
		buf.WriteString(fmt.Sprintf("// %s event from IDL\n", e.Name))
		buf.WriteString(fmt.Sprintf("type %sEvent struct {\n", e.Name))
		for _, f := range e.Fields {
			goTy := idlTypeToGo(f.Type)
			buf.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", toPascal(f.Name), goTy, f.Name))
		}
		buf.WriteString("}\n\n")
	}

	return buf.String(), nil
}

func generateClient(parsed *idl.IDL, pkg string) (string, error) {
	return generateClientSimple(parsed, pkg)
}

func generateClientSimple(parsed *idl.IDL, pkg string) (string, error) {
	var buf strings.Builder
	buf.WriteString("// Code generated by go-anchor. DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkg))
	buf.WriteString(`import (
	"github.com/gagliardetto/solana-go"
	"github.com/gagliardetto/solana-go/rpc"
	"go-solana-anchor/client"
	"go-solana-anchor/idl"
)

`)
	buf.WriteString(fmt.Sprintf("// ProgramID is the %s program address.\n", parsed.Metadata.Name))
	buf.WriteString(fmt.Sprintf("var ProgramID = solana.MustPublicKeyFromBase58(%q)\n\n", parsed.Address))
	buf.WriteString("// NewClient creates a typed client. Pass IDL bytes (e.g. from idl.Parse) and RPC client.\n")
	buf.WriteString("func NewClient(idlData *idl.IDL, rpcClient *rpc.Client) *Client {\n")
	buf.WriteString("\tprog := client.NewProgram(idlData, ProgramID, rpcClient)\n")
	buf.WriteString("\treturn &Client{Program: prog}\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// Client wraps the generic Program with typed methods.\n")
	buf.WriteString("type Client struct {\n\t*client.Program\n}\n\n")

	for _, inst := range parsed.Instructions {
		methodName := toPascal(inst.Name)
		accStruct := methodName + "Accounts"
		buf.WriteString(fmt.Sprintf("// %s holds accounts for %s.\n", accStruct, inst.Name))
		buf.WriteString(fmt.Sprintf("type %s struct {\n", accStruct))
		for _, a := range inst.Accounts {
			buf.WriteString(fmt.Sprintf("\t%s solana.PublicKey\n", toPascal(a.Name)))
		}
		buf.WriteString("}\n\n")
		buf.WriteString(fmt.Sprintf("// %s builds the %s instruction.\n", methodName, inst.Name))
		hasArgs := len(inst.Args) > 0
		if hasArgs {
			buf.WriteString(fmt.Sprintf("func (c *Client) %s(accounts %s, args []byte) (solana.Instruction, error) {\n", methodName, accStruct))
		} else {
			buf.WriteString(fmt.Sprintf("func (c *Client) %s(accounts %s) (solana.Instruction, error) {\n", methodName, accStruct))
		}
		buf.WriteString("\tm := map[string]solana.PublicKey{\n")
		for _, a := range inst.Accounts {
			buf.WriteString(fmt.Sprintf("\t\t%q: accounts.%s,\n", a.Name, toPascal(a.Name)))
		}
		buf.WriteString("\t}\n")
		if hasArgs {
			buf.WriteString("\treturn c.BuildInstruction(\"" + inst.Name + "\", args, m)\n")
		} else {
			buf.WriteString("\treturn c.BuildInstruction(\"" + inst.Name + "\", nil, m)\n")
		}
		buf.WriteString("}\n\n")
	}
	return buf.String(), nil
}

func generateErrors(parsed *idl.IDL, pkg string) (string, error) {
	var buf strings.Builder
	buf.WriteString("// Code generated by go-anchor. DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkg))
	buf.WriteString("import \"fmt\"\n\n")
	buf.WriteString("// Program error codes from IDL.\n")
	buf.WriteString("const (\n")
	for _, e := range parsed.Errors {
		buf.WriteString(fmt.Sprintf("\tErr%s uint64 = %d\n", toPascal(e.Name), e.Code))
	}
	buf.WriteString(")\n\n")
	buf.WriteString("// ErrorCodeToError maps program error code to Go error.\n")
	buf.WriteString("func ErrorCodeToError(code uint64) error {\n")
	buf.WriteString("\tswitch code {\n")
	for _, e := range parsed.Errors {
		msg := e.Msg
		if msg == "" {
			msg = e.Name
		}
		buf.WriteString(fmt.Sprintf("\tcase %d:\n\t\treturn fmt.Errorf(\"%s: %%s\", %q)\n", e.Code, e.Name, msg))
	}
	buf.WriteString("\tdefault:\n\t\treturn fmt.Errorf(\"unknown error: %%d\", code)\n")
	buf.WriteString("\t}\n}\n")
	return buf.String(), nil
}
